"""review box model

Revision ID: 06847469412e
Revises: e9229f830f15
Create Date: 2023-10-30 18:12:33.266179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06847469412e'
down_revision = 'e9229f830f15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box', sa.Column('cover', sa.String(), nullable=True))
    op.add_column('box', sa.Column('status', sa.Enum('open', 'closed', 'done', name='objectivestatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('box', 'status')
    op.drop_column('box', 'cover')
    # ### end Alembic commands ###
