"""character with user

Revision ID: 1d83b2ea78ce
Revises: 311910cb7c37
Create Date: 2023-11-01 14:24:25.095781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d83b2ea78ce'
down_revision = '311910cb7c37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_character_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_character_id', sa.Integer(), nullable=False),
    sa.Column('ref_data', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['request_character_id'], ['request_character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'request_character_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_character_user')
    # ### end Alembic commands ###
