"""update primary keys models

Revision ID: 23c8ea61a467
Revises: 2b55fe4a9a23
Create Date: 2023-11-05 14:09:49.261359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c8ea61a467'
down_revision = '2b55fe4a9a23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_user', 'ref_data',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('help_user', 'ref_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('history_user', 'ref_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('objective_user', 'ref_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('request_character_user', 'ref_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_character_user', 'ref_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('objective_user', 'ref_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('history_user', 'ref_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('help_user', 'ref_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event_user', 'ref_data',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
