"""review help model

Revision ID: 311910cb7c37
Revises: 19aca860e66f
Create Date: 2023-11-01 11:09:04.217293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '311910cb7c37'
down_revision = '19aca860e66f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('help', 'status')
    op.drop_column('help', 'hints')
    op.drop_column('help', 'ref')
    op.drop_column('help', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('help', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('help', sa.Column('ref', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('help', sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('help', sa.Column('status', postgresql.ENUM('open', 'closed', 'done', name='helpstatus'), autoincrement=False, nullable=True))
    op.drop_column('help', 'data')
    # ### end Alembic commands ###
