"""add objective table

Revision ID: 33661127a4ca
Revises: 4ee187cc25db
Create Date: 2023-10-22 23:02:55.670721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33661127a4ca'
down_revision = '4ee187cc25db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'done', name='objectivestatus'), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objective_id'), 'objective', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objective_id'), table_name='objective')
    op.drop_table('objective')
    sa.Enum('open', 'closed', 'done', name='objectivestatus').drop(op.get_bind())
    # ### end Alembic commands ###
