"""review character

Revision ID: 57e627db3159
Revises: e709bd2efccf
Create Date: 2023-10-30 16:49:17.181232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e627db3159'
down_revision = 'e709bd2efccf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_character', sa.Column('text', sa.JSON(), nullable=True))
    op.add_column('request_character', sa.Column('src_comment', sa.String(), nullable=True))
    op.add_column('request_character', sa.Column('src_audio', sa.String(), nullable=True))
    op.add_column('request_character', sa.Column('src_transcript', sa.String(), nullable=True))
    op.add_column('request_character', sa.Column('src', sa.String(), nullable=True))
    op.add_column('request_character', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('request_character', 'result')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_character', sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('request_character', 'title')
    op.drop_column('request_character', 'src')
    op.drop_column('request_character', 'src_transcript')
    op.drop_column('request_character', 'src_audio')
    op.drop_column('request_character', 'src_comment')
    op.drop_column('request_character', 'text')
    # ### end Alembic commands ###
