"""add help user table

Revision ID: 63e72a394cd1
Revises: 1d83b2ea78ce
Create Date: 2023-11-01 19:54:08.893659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e72a394cd1'
down_revision = '1d83b2ea78ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('help_id', sa.Integer(), nullable=False),
    sa.Column('ref_data', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['help_id'], ['help.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'help_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help_user')
    # ### end Alembic commands ###
