"""update primary keys

Revision ID: 879e2aaf3dcd
Revises: 23c8ea61a467
Create Date: 2023-11-05 21:39:25.567900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '879e2aaf3dcd'
down_revision = '23c8ea61a467'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE request_character_user DROP CONSTRAINT IF EXISTS request_character_user_pkey;")
    op.execute("ALTER TABLE request_character_user ADD CONSTRAINT request_character_user_pkey PRIMARY KEY (user_id, request_character_id, ref_data);")

    op.execute("ALTER TABLE event_user DROP CONSTRAINT IF EXISTS event_user_pkey;")
    op.execute("ALTER TABLE event_user ADD CONSTRAINT event_user_pkey PRIMARY KEY (user_id, event_id, ref_data);")

    op.execute("ALTER TABLE help_user DROP CONSTRAINT IF EXISTS help_user_pkey;")
    op.execute("ALTER TABLE help_user ADD CONSTRAINT help_user_pkey PRIMARY KEY (user_id, help_id, ref_data);")

    op.execute("ALTER TABLE history_user DROP CONSTRAINT IF EXISTS history_user_pkey;")
    op.execute("ALTER TABLE history_user ADD CONSTRAINT history_user_pkey PRIMARY KEY (user_id, history_id, ref_data);")

    op.execute("ALTER TABLE objective_user DROP CONSTRAINT IF EXISTS objective_user_pkey;")
    op.execute("ALTER TABLE objective_user ADD CONSTRAINT objective_user_pkey PRIMARY KEY (user_id, objective_id, ref_data);")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE request_character_user DROP CONSTRAINT IF EXISTS request_character_user_pkey;")
    op.execute("ALTER TABLE request_character_user ADD CONSTRAINT request_character_user_pkey PRIMARY KEY (user_id, request_character_id);")

    op.execute("ALTER TABLE event_user DROP CONSTRAINT IF EXISTS event_user_pkey;")
    op.execute("ALTER TABLE event_user ADD CONSTRAINT event_user_pkey PRIMARY KEY (user_id, event_id);")

    op.execute("ALTER TABLE help_user DROP CONSTRAINT IF EXISTS help_user_pkey;")
    op.execute("ALTER TABLE help_user ADD CONSTRAINT help_user_pkey PRIMARY KEY (user_id, help_id);")

    op.execute("ALTER TABLE history_user DROP CONSTRAINT IF EXISTS history_user_pkey;")
    op.execute("ALTER TABLE history_user ADD CONSTRAINT history_user_pkey PRIMARY KEY (user_id, history_id);")

    op.execute("ALTER TABLE objective_user DROP CONSTRAINT IF EXISTS objective_user_pkey;")
    op.execute("ALTER TABLE objective_user ADD CONSTRAINT objective_user_pkey PRIMARY KEY (user_id, objective_id);")
    # ### end Alembic commands ###
