"""add history table

Revision ID: a850b1ef5f69
Revises: 33661127a4ca
Create Date: 2023-10-22 23:15:28.060241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a850b1ef5f69'
down_revision = '33661127a4ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('poster', sa.String(), nullable=True),
    sa.Column('img1', sa.String(), nullable=True),
    sa.Column('img2', sa.String(), nullable=True),
    sa.Column('src_audio', sa.String(), nullable=True),
    sa.Column('src_transcript', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['box.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_id'), 'history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_id'), table_name='history')
    op.drop_table('history')
    # ### end Alembic commands ###
