"""change data type

Revision ID: c9c3c5f5968f
Revises: 57e627db3159
Create Date: 2023-10-30 17:16:12.334501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9c3c5f5968f'
down_revision = '57e627db3159'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_character', sa.Column('data', sa.JSON(), nullable=True))
    op.drop_column('request_character', 'src_comment')
    op.drop_column('request_character', 'src_audio')
    op.drop_column('request_character', 'src_transcript')
    op.drop_column('request_character', 'status')
    op.drop_column('request_character', 'text')
    op.drop_column('request_character', 'title')
    op.drop_column('request_character', 'ask')
    op.drop_column('request_character', 'src')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_character', sa.Column('src', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('request_character', sa.Column('ask', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('request_character', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('request_character', sa.Column('text', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('request_character', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('request_character', sa.Column('src_transcript', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('request_character', sa.Column('src_audio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('request_character', sa.Column('src_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('request_character', 'data')
    # ### end Alembic commands ###
