"""review help model

Revision ID: e9229f830f15
Revises: fe123ac5dcde
Create Date: 2023-10-30 18:07:26.000266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9229f830f15'
down_revision = 'fe123ac5dcde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hint_id', table_name='hint')
    op.drop_table('hint')
    op.add_column('help', sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quizz', sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quizz', sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('quizz', 'choices')
    op.drop_column('quizz', 'image_question')
    op.drop_column('quizz', 'explanation')
    op.drop_column('quizz', 'image_answer')
    op.drop_column('quizz', 'question')
    op.drop_column('quizz', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizz', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quizz', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quizz', sa.Column('image_answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('quizz', sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('quizz', sa.Column('image_question', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('quizz', sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('quizz', 'answers')
    op.drop_column('quizz', 'questions')
    op.drop_column('help', 'hints')
    op.create_table('hint',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('help_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['help_id'], ['help.id'], name='hint_help_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hint_pkey')
    )
    op.create_index('ix_hint_id', 'hint', ['id'], unique=False)
    # ### end Alembic commands ###
